name:                cadregascript
version:             0.1.0.0
github:              "MicheleRiva/cadregascript"
license:             BSD3
author:              "Michele Riva"
maintainer:          "ciao@micheleriva.it"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MicheleRiva/cadregascript#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cadregascript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cadregascript

tests:
  cadregascript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cadregascript
